# === Meowcoin Upptime Configuration ===
owner: meowcoin-foundation
repo: meowcoin-status

sites:
  - name: Meowcoin API
    url: https://api.mewccrypto.com/health

  - name: Meowcoin Explorer
    url: https://explorer.mewccrypto.com

  - name: Meowcoin RPC (Proxy)
    url: https://mewc-rpc-mainnet.mewccrypto.com
    check: "http"

status-website:
  cname: status.mewccrypto.com
  logoUrl: https://www.mewccrypto.com/MeowcoinR2.svg
  name: Meowcoin Status
  introTitle: "Meowcoin Network Status"
  introMessage: >
    This page shows real-time uptime for the Meowcoin API, Explorer, RPC proxy,
    and other core infrastructure — powered entirely by Upptime and GitHub Actions.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/meowcoin-foundation/meowcoin-status
