# === Meowcoin Upptime Configuration ===
owner: meowcoin-foundation
repo: meowcoin-status

sites:
  - name: Meowcoin API
    url: https://api.mewccrypto.com/health

  - name: Meowcoin Explorer (Primary)
    url: https://explorer.mewccrypto.com

  - name: Meowcoin Explorer (Fallback)
    url: https://explorer2.mewccrypto.com

  - name: Blockbook Server
    url: https://blockbook.mewccrypto.com
    check: "http"

  - name: Meowcoin RPC (Proxy)
    url: https://mewc-rpc-mainnet.mewccrypto.com
    check: "http"

  - name: Burn Explorer
    url: https://burn.mewccrypto.com

  - name: PawPledge Donation Platform
    url: https://pawpledge.mewccrypto.com

  - name: ElectrumX - meowcoinelectrum.xyz
    url: meowcoinelectrum.xyz
    port: 50002
    check: "tcp-ping"

  - name: ElectrumX - electrum.mewccrypto.com
    url: electrum.mewccrypto.com
    port: 50002
    check: "tcp-ping"

  - name: ElectrumX - Topper
    url: meowelectrum2.testtopper.biz
    port: 50002
    check: "tcp-ping"

status-website:
  cname: status.mewccrypto.com
  logoUrl: https://www.mewccrypto.com/MeowcoinR2.svg
  name: Meowcoin Status
  introTitle: "Meowcoin Network Status"
  introMessage: >
    This page shows real-time uptime for the Meowcoin API, Explorers,
    Blockbook backend, RPC proxy, Burn Explorer, PawPledge donations,
    and other core infrastructure — fully automated by Upptime and GitHub Actions.

  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/meowcoin-foundation/meowcoin-status
